---
- name: Deploy application
  hosts: localhost
  roles:
    - app_deploy
  vars:
    cloud_sql_proxy_image: 'gcr.io/cloudsql-docker/gce-proxy:1.33.1'
    config_data: "{{ lookup('file', '../schedule-config/config.json') | from_json }}"

# - name: Deploy ingress
#   hosts: localhost
#   roles:
#     - cert_manager
#     - nginx_ingress_controller