---
# - name: Restore database to Cloud SQL
#   hosts: localhost
#   roles:
#     - restore_db_from_dump
#   vars:
#     db_dump_file: "./2024-08-19.dump"

- name: Deploy application
  hosts: localhost
  roles:
    - app_deploy
  vars:
    config_data: "{{ lookup('file', '../schedule-config/config.json') | from_json }}"

# - name: Deploy ingress
#   hosts: localhost
#   roles:
#     - cert_manager
#     - nginx_ingress_controller