- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: "{{ env }}"
    api_version: v1
    kind: Namespace
    state: present
  tags: 
    - namespaces

- name: Deploy ConfigMap
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/configmap.yaml.j2"
  loop: "{{ config_data.configmaps }}"
  tags:
    - configmap

- name: Deploy Secret
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/secrets.yaml.j2"
  loop: "{{ config_data.secrets }}"
  tags:
    - secret

- name: Deploy Service
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/service.yaml.j2"
  loop: "{{ config_data.services }}"
  tags:
    - service

- name: Deploy Deployment
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/deployment.yaml.j2"
  loop: "{{ config_data.deployments }}"
  tags:
    - deployment

- name: Apply Ingress
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/app-ingress.yaml.j2"
  loop: "{{ config_data.ingress }}"
  tags:
    - ingress

- name: Apply Cert
  kubernetes.core.k8s:
    state: present
    template: "{{ role_path }}/templates/app-certificate.yaml.j2"
    namespace: "{{ namespace | default('app-ingress') }}"
  loop: "{{ config_data.ingress }}"
  tags:
    - cert