- name: Add ingress-nginx Helm repo
  community.kubernetes.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx

- name: Install ingress-nginx controller with LoadBalancer and named static IP (GCP)
  community.kubernetes.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: "{{ ingress_namespace }}"
    create_namespace: true
    values:
      controller:
        kind: Deployment
        service:
          type: LoadBalancer
          loadBalancerIP: "{{ hostvars[inventory_hostname].get(env ~ '-gke-ingress-ip', 'IP_NOT_DEFINED') }}"
        ingressClassResource:
          name: "{{ ingress_class_name }}"
          enabled: true
          default: true
    wait: true
    update_repo_cache: true