---
# Default configurations
namespaces: [
    {
      "name": "intproject"
    }
]
configmaps: [
  {
    "name": "backend-config",
    "data": {
      DB_HOST: "<db-url>",
      DB_PORT: "5432",
      DB_NAME: "maindb",
      REDIS_HOST: "redis",
      REDIS_PORT: "6379"
    },
    "namespace": "intproject"
  }
]
secrets: [
  {
    "name": "backend-secret",
    "data": {
      "DB_USER": "user",
      "DB_PASSWORD": "password"
    },
    "namespace": "intproject"
  }
]
services: [
    {
      "name": "redis",
      "app": "redis",
      "type": "ClusterIP",
      "port": 6379,
      "target_port": 6379,
      "protocol": "TCP",
      "namespace": "intproject"
    },
    {
      "name": "backend",
      "app": "backend",
      "type": "NodePort",
      "port": 8080,
      "target_port": 8080,
      "protocol": "TCP",
      "node_port": 31111,
      "namespace": "intproject"
    }
]
deployments:  [
    {
      "name": "redis",
      "app": "redis",
      "image": "redis:alpine",
      "version": "7",
      "replicas": 1,
      "port": 6379,
      "config_refs": ["redis-config"],
      "secret_refs": [],
      "namespace": "intproject"
    },
    {
      "name": "backend",
      "app": "backend",
      "image": "dolvladzio/backend:2025-06-23-07-05-57",
      "version": "2",
      "replicas": 1,
      "port": 8080,
      "config_refs": ["backend-config"],
      "secret_refs": ["backend-secret"],
      "namespace": "intproject"
    }
]
ingress: [
    {
      name: app-tls-secret,
      cluster_issuer_name_map: {staging: "letsencrypt-staging", production: "letsencrypt-production"},
      ingress_class_name: nginx,
      certificate_secret_map: { staging: "tls-secret-stag", production: "tls-secret-prod" },
      app_name: my-app,
      namespace: "intproject",
      ingress_name: app-ingress,
      domain: anfox.pp.ua,
      tls_secret_name_map: {staging: "app-secret-tls-stag", production: "app-secret-tls-prod"},
      ingress_namespace: intproject
    }
]