---
- name: Update apt cache
  become: yes
  apt:
    update_cache: yes

- name: Install PostgreSQL client
  become: yes
  apt:
    name: postgresql-client
    state: present

- name: Copy DB dump to bastion VM
  copy:
    src: "{{ db_dump_file }}"
    dest:  "{{ db_dump_file_dest }}"
    mode: '0644'

- name: Restore PostgreSQL database from dump
  become: yes
  command: >
    psql -h {{ db_host }}
          -U {{ db_user }}
          -d {{ db_name }}
          -f {{ db_dump_file_dest }}
  environment:
    PGPASSWORD: "{{ db_password }}"