name: "Run The Ansible Role: App Deploy"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy-frontend, deploy-backend ]

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY  }}'

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Clone another repo
        run: |
          git clone https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/DolVladzio/schedule-config.git ../schedule-config

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
          pip install kubernetes
          ansible-galaxy collection install community.kubernetes
          ansible-galaxy collection install community.general
          gcloud components install gke-gcloud-auth-plugin

      - name: Getting access to the GKE Cluster
        run: |
          gcloud container clusters get-credentials ${{ secrets.GCP_CLUSTER_NAME }} --zone ${{ secrets.GCP_CLUSTER_REGION }}-a --project ${{ secrets.GCP_PROJECT_ID }}

      - name: Copy the inventory.ini from the GCP bucket
        run: gsutil cp gs://${{ secrets.ANSBILE_BUCKET_NAME }}/inventory.ini inventory/inventory.ini

      - name: Setting up current version of images
        run: |
          FRONTEND_IMAGE=$(kubectl get deployment frontend -n ${{ secrets.K8S_NAMESPACE_NAME }} -o jsonpath='{.spec.template.spec.containers[0].image}')
          BACKEND_IMAGE=$(kubectl get deployment backend -n ${{ secrets.K8S_NAMESPACE_NAME }} -o jsonpath='{.spec.template.spec.containers[0].image}')
      
      - name: Update frontend image if needed
        if: github.event.action == 'deploy-frontend'
        run: |
          FRONTEND_IMAGE=${{ github.event.client_payload.frontend_image }}

      - name: Update backend image if needed
        if: github.event.action == 'deploy-backend'
        run: |
          BACKEND_IMAGE=${{ github.event.client_payload.backend_image }}

      - name: Run the ansible playbook
        run: |
          ansible-playbook ingress_deploy.yml
          ansible-playbook app_deploy.yml \
            -e "frontend_image=${FRONTEND_IMAGE} backend_image=${BACKEND_IMAGE} env=production"