name: "Run The Ansible Role: Restore DB"

on:
  push:
    branches: [ dev ]
  pull_request:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_KEY  }}'

      # Optional: setup gcloud CLI (if you use gcloud commands)
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Show Ansible version
        run: ansible --version

      - name: Copy the db dump from the GCP bucket
        run: gsutil cp gs://maindb_dump/2024-08-19.dump ./db-dump.sql

      # - name: Run Ansible playbook
      #   run: |
      #     ansible-playbook -i inventory.ini restore_db.yml -e "db_dump_file=${{ secrets.DUMP_FILE_NAME }}"
